#Digital image recognition Case Study

##Step 1 Research goal: can we classify numbers of images as the correct numbers. 

##Imports

In [6]:
from sklearn.datasets import load_digits
import pylab as pl 

##Step 2 & 3: retrieving data & cleansing

data is already present in the sci-kit learn library.
The data is inherently "unclean" as the images are never a perfect representation of the number.
The whole excercise is to deal with this.

In [7]:
digits = load_digits() 

##Step 4 : data exploration

###Show image number 0 (which is also "0")

In [8]:
pl.gray()
pl.matshow(digits.images[0])    
pl.show()

###Show matrix representation of the number 0

In [9]:
digits.images[0]

array([[  0.,   0.,   5.,  13.,   9.,   1.,   0.,   0.],
       [  0.,   0.,  13.,  15.,  10.,  15.,   5.,   0.],
       [  0.,   3.,  15.,   2.,   0.,  11.,   8.,   0.],
       [  0.,   4.,  12.,   0.,   0.,   8.,   8.,   0.],
       [  0.,   5.,   8.,   0.,   0.,   9.,   8.,   0.],
       [  0.,   4.,  11.,   0.,   1.,  12.,   7.,   0.],
       [  0.,   2.,  14.,   5.,  10.,  12.,   0.,   0.],
       [  0.,   0.,   6.,  13.,  10.,   0.,   0.,   0.]])

##Step 5: data modelling

### Supervised learning: classifying images of numbers

In [10]:
from sklearn.cross_validation import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix
import pylab as plt

y = digits.target #A

n_samples = len(digits.images) #B
X= digits.images.reshape((n_samples, -1)) #B

print X

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0) #C

gnb = GaussianNB()#D
fit = gnb.fit(X_train,y_train)#E
predicted = fit.predict(X_test)#F
confusion_matrix(y_test, predicted)#G

[[  0.   0.   5. ...,   0.   0.   0.]
 [  0.   0.   0. ...,  10.   0.   0.]
 [  0.   0.   0. ...,  16.   9.   0.]
 ..., 
 [  0.   0.   1. ...,   6.   0.   0.]
 [  0.   0.   2. ...,  12.   0.   0.]
 [  0.   0.  10. ...,  12.   1.   0.]]


array([[37,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 39,  0,  0,  0,  0,  1,  0,  3,  0],
       [ 0,  9, 17,  3,  0,  0,  0,  0, 15,  0],
       [ 0,  0,  0, 38,  0,  0,  0,  2,  5,  0],
       [ 0,  1,  0,  0, 27,  0,  2,  8,  0,  0],
       [ 0,  1,  0,  1,  0, 43,  0,  3,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 52,  0,  0,  0],
       [ 0,  0,  0,  0,  1,  0,  0, 47,  0,  0],
       [ 0,  5,  0,  1,  0,  1,  0,  4, 37,  0],
       [ 0,  2,  0,  7,  1,  0,  0,  3,  7, 27]])

In [ ]:
#A Step 1: Select target variable
#B Step 2: Prepare data. Reshape adapts the matrix form. This method could for instance turn a 10x10 matrix into 100 vectors.
#C Step 3: Split into a test set and training set
#D Step 4: Select a Naïve Bayes classified; use a Gaussian distribution to estimate the probability
#E Step 5: Fit the data
#F Step 6: Predict the data for unseen data
#G Step 7: Create the confusion matrix

##Step 6: Presentation & automation

###Visually showing the predictions

In [11]:
images_and_predictions = list(zip(digits.images, fit.predict(X)))#A
for index, (image, prediction) in enumerate(images_and_predictions[:6]):#B
    plt.subplot(6, 3 ,index + 5)#C
    plt.axis('off')#D
    plt.imshow(image, cmap=plt.cm.gray_r, interpolation='nearest')#E
    plt.title('Prediction: %i' % prediction)#f
plt.show()#G

In [12]:
images_and_predictions

[(array([[  0.,   0.,   5.,  13.,   9.,   1.,   0.,   0.],
         [  0.,   0.,  13.,  15.,  10.,  15.,   5.,   0.],
         [  0.,   3.,  15.,   2.,   0.,  11.,   8.,   0.],
         [  0.,   4.,  12.,   0.,   0.,   8.,   8.,   0.],
         [  0.,   5.,   8.,   0.,   0.,   9.,   8.,   0.],
         [  0.,   4.,  11.,   0.,   1.,  12.,   7.,   0.],
         [  0.,   2.,  14.,   5.,  10.,  12.,   0.,   0.],
         [  0.,   0.,   6.,  13.,  10.,   0.,   0.,   0.]]), 0),
 (array([[  0.,   0.,   0.,  12.,  13.,   5.,   0.,   0.],
         [  0.,   0.,   0.,  11.,  16.,   9.,   0.,   0.],
         [  0.,   0.,   3.,  15.,  16.,   6.,   0.,   0.],
         [  0.,   7.,  15.,  16.,  16.,   2.,   0.,   0.],
         [  0.,   0.,   1.,  16.,  16.,   3.,   0.,   0.],
         [  0.,   0.,   1.,  16.,  16.,   6.,   0.,   0.],
         [  0.,   0.,   1.,  16.,  16.,   6.,   0.,   0.],
         [  0.,   0.,   0.,  11.,  16.,  10.,   0.,   0.]]), 1),
 (array([[  0.,   0.,   0.,   4.,  15.,  12.

In [ ]:
#A store the number image matrix and its prediction (as a number) together in an array
#B loop through the first 7 images
#C add an extra subplot on a 6 by 3 plot grid. This code could be simplified as:
#plt.subplot(3, 2 ,index) but this looks visually more appealing. 
#D don't show an axis
#E show the image in grayscale
#F show the predicted value as the title to the shown image
#G show the full plot that is now populated with 6 subplots

#Wine Quality Case Study

##Imports

In [13]:
import pandas as pd
from sklearn import preprocessing
from sklearn.decomposition import PCA
import pylab as plt
from sklearn import preprocessing

##Step 2: retrieving data

###Data is drawn from an online machine learning data set archive

In [14]:
url = 'http://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv' #A 
data = pd.read_csv(url, sep= ";")#B

In [16]:
#A Download location of wine-quality dataset
#B read in the csv data , it is separated by semi-colon

##Step 3: data cleansing

###Split dataset in independent (X) and dependent (y) variables

In [15]:
X = data[[u'fixed acidity', u'volatile acidity', u'citric acid', 
      u'residual sugar', u'chlorides', u'free sulfur dioxide', 
      u'total sulfur dioxide', u'density', u'pH', u'sulphates', 
      u'alcohol']] #C
y = data.quality #D 

In [ ]:
#C X is a matrix of predictor variables. These variables are wine properties like density, alcohol presence etc.
#D y is a vector and represents the dependent variable (target variable). y is the perceived wine quality.

###Variable standardisation 

In [16]:
X = preprocessing.StandardScaler().fit(X).transform(X) #E

In [17]:
#E When standardizing data, the following formula is applied to every datapoint:
# z = (x-μ)/σ 
# z is the new obsevation value , x the old one. μ is the mean and σ the standard deviation. 
# PCA of a data matrix is easier to interpret when the columns have first been centered by their means. 

##Step 4: data exploration

###principal component analysis (PCA) for dimentionality reduction

In [17]:
model = PCA() #A
results = model.fit(X) #B
Z = results.transform(X) #C
plt.plot(results.explained_variance_) #D
plt.show() #E

In [1]:
#A create an instance of principal component analysis class
#B apply PCA on the predictor variables to see if they can be compacted into less variables
#C turn the result into an actual array so we can use the newly created data
#D plot the explained variance in variables, this plot is called a scree plot
#E show the plot

In [10]:
print(results.components_)

[[ 0.48931422 -0.23858436  0.46363166  0.14610715  0.21224658 -0.03615752
   0.02357485  0.39535301 -0.43851962  0.24292133 -0.11323206]
 [-0.11050274  0.27493048 -0.15179136  0.27208024  0.14805156  0.51356681
   0.56948696  0.23357549  0.00671079 -0.03755392 -0.38618096]
 [ 0.12330157  0.44996253 -0.23824707 -0.10128338  0.09261383 -0.42879287
  -0.3224145   0.33887135 -0.05769735 -0.27978615 -0.47167322]
 [-0.22961737  0.07895978 -0.07941826 -0.37279256  0.66619476 -0.04353782
  -0.03457712 -0.17449976 -0.00378775  0.55087236 -0.12218109]
 [ 0.08261366 -0.21873452  0.05857268 -0.73214429 -0.2465009   0.15915198
   0.22246456 -0.15707671 -0.26752977 -0.22596222 -0.35068141]
 [-0.10147858 -0.41144893 -0.06959338 -0.04915555 -0.30433857  0.01400021
  -0.13630755  0.3911523   0.52211645  0.38126343 -0.36164504]
 [ 0.35022736  0.5337351  -0.10549701 -0.29066341 -0.37041337  0.11659611
   0.09366237  0.17048116  0.02513762  0.44746911  0.3276509 ]
 [-0.17759545 -0.07877531 -0.37751558  0.

##step 3 revisited: data preparation

###Using the PCA analysis we will compress the data to just a few principal components

In [11]:
pd.DataFrame(results.components_, columns=list([u'fixed acidity', u'volatile acidity', u'citric acid', u'residual sugar', u'chlorides', u'free sulfur dioxide',  u'total sulfur dioxide', u'density', u'pH', u'sulphates',  u'alcohol']))

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0        0.489314         -0.238584     0.463632        0.146107   0.212247   
1       -0.110503          0.274930    -0.151791        0.272080   0.148052   
2        0.123302          0.449963    -0.238247       -0.101283   0.092614   
3       -0.229617          0.078960    -0.079418       -0.372793   0.666195   
4        0.082614         -0.218735     0.058573       -0.732144  -0.246501   
5       -0.101479         -0.411449    -0.069593       -0.049156  -0.304339   
6        0.350227          0.533735    -0.105497       -0.290663  -0.370413   
7       -0.177595         -0.078775    -0.377516        0.299845  -0.357009   
8        0.194021         -0.129110    -0.381450        0.007523   0.111339   
9        0.249523         -0.365925    -0.621677       -0.092872   0.217671   
10       0.639691          0.002389    -0.070910        0.184030   0.053065   

    free sulfur dioxide  total sulfur dioxide   density        pH  sulphates  \
0             -0.036158              0.023575  0.395353 -0.438520   0.242921   
1              0.513567              0.569487  0.233575  0.006711  -0.037554   
2             -0.428793             -0.322415  0.338871 -0.057697  -0.279786   
3             -0.043538             -0.034577 -0.174500 -0.003788   0.550872   
4              0.159152              0.222465 -0.157077 -0.267530  -0.225962   
5              0.014000             -0.136308  0.391152  0.522116   0.381263   
6              0.116596              0.093662  0.170481  0.025138   0.447469   
7             -0.204781              0.019036 -0.239223 -0.561391   0.374604   
8              0.635405             -0.592116  0.020719 -0.167746  -0.058367   
9             -0.248483              0.370750  0.239990  0.010970  -0.112320   
10            -0.051421              0.068702 -0.567332  0.340711   0.069555   

     alcohol  
0  -0.113232  
1  -0.386181  
2  -0.471673  
3  -0.122181  
4  -0.350681  
5  -0.361645  
6   0.327651  
7  -0.217626  
8   0.037603  
9   0.303015  
10 -0.314526

In [ ]:
#The table shows how each original variable loads to the newly created factors. 

In [19]:
X

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
5               7.4             0.660         0.00             1.8      0.075   
6               7.9             0.600         0.06             1.6      0.069   
7               7.3             0.650         0.00             1.2      0.065   
8               7.8             0.580         0.02             2.0      0.073   
9               7.5             0.500         0.36             6.1      0.071   
10              6.7             0.580         0.08             1.8      0.097   
11              7.5             0.500         0.36             6.1      0.071   
12              5.6             0.615         0.00             1.6      0.089   
13              7.8             0.610         0.29             1.6      0.114   
14              8.9             0.620         0.18             3.8      0.176   
15              8.9             0.620         0.19             3.9      0.170   
16              8.5             0.280         0.56             1.8      0.092   
17              8.1             0.560         0.28             1.7      0.368   
18              7.4             0.590         0.08             4.4      0.086   
19              7.9             0.320         0.51             1.8      0.341   
20              8.9             0.220         0.48             1.8      0.077   
21              7.6             0.390         0.31             2.3      0.082   
22              7.9             0.430         0.21             1.6      0.106   
23              8.5             0.490         0.11             2.3      0.084   
24              6.9             0.400         0.14             2.4      0.085   
25              6.3             0.390         0.16             1.4      0.080   
26              7.6             0.410         0.24             1.8      0.080   
27              7.9             0.430         0.21             1.6      0.106   
28              7.1             0.710         0.00             1.9      0.080   
29              7.8             0.645         0.00             2.0      0.082   
...             ...               ...          ...             ...        ...   
1569            6.2             0.510         0.14             1.9      0.056   
1570            6.4             0.360         0.53             2.2      0.230   
1571            6.4             0.380         0.14             2.2      0.038   
1572            7.3             0.690         0.32             2.2      0.069   
1573            6.0             0.580         0.20             2.4      0.075   
1574            5.6             0.310         0.78            13.9      0.074   
1575            7.5             0.520         0.40             2.2      0.060   
1576            8.0             0.300         0.63             1.6      0.081   
1577            6.2             0.700         0.15             5.1      0.076   
1578            6.8             0.670         0.15             1.8      0.118   
1579            6.2             0.560         0.09             1.7      0.053   
1580            7.4             0.350         0.33             2.4      0.068   
1581            6.2             0.560         0.09             1.7      0.053   
1582            6.1             0.715         0.10             2.6      0.053   
1583            6.2             0.460         0.29             2.1      0.074   
1584            6.7             0.320         0.44             2.4      0.061   
1585            7.2             0.390         0.44             2.6      0.066   
1586            7.5             0.310

##Step 5: data modelling

###Wine score prediction without  principal components analysis

In [22]:
from sklearn.cross_validation import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix
import pylab as plt

gnb = GaussianNB() #A
fit = gnb.fit(X,y) #B             
pred = fit.predict(X) #C            
print confusion_matrix(pred,y)#D      

[[  3   1   4   0   0   0]
 [  2   8  26  19   1   0]
 [  4  29 456 185  12   0]
 [  1  13 171 318  74   5]
 [  0   1  24 111 110  11]
 [  0   1   0   5   2   2]]


In [23]:
print confusion_matrix(pred,y).trace()#E

897


In [ ]:
#A Use a Gaussian distribution Naïve Bayes classifier for estimation
#B Fit the data
#C Predict the data for unseen data
#D Study the confusion matrix
#E count of all correctly classified cases: all counts on the trace or diagonal summed up

###Wine score prediction with increasing number of Principal components

In [14]:
predicted_correct = []#A
for i in range(1,10):#B
    model = PCA(n_components = i)#C
    results = model.fit(X)#D
    Z = results.transform(X) #E
    fit = gnb.fit(Z,y) #F
    pred = fit.predict(Z)#G
    predicted_correct.append(confusion_matrix(pred,y).trace())#H
    print predicted_correct #I
plt.plot(predicted_correct) #J
plt.show()#K

[712]
[712, 816]
[712, 816, 903]
[712, 816, 903, 893]
[712, 816, 903, 893, 904]
[712, 816, 903, 893, 904, 920]
[712, 816, 903, 893, 904, 920, 930]
[712, 816, 903, 893, 904, 920, 930, 927]
[712, 816, 903, 893, 904, 920, 930, 927, 937]


In [ ]:
#A array will be filled with correctly predicted observations
#B loop through the first 10 detected principal components
#C istantiate a PCA model with 1 component (first iteration) up to 10 components (in 10th iteration)
#D fit the PCA model on the x-variables (features)
#E Z is the result in matrix form (actually an array filled with arrays)
#F Use a Gaussian distribution Naïve Bayes classifier for estimation.
#G the actual prediction itself using the fitted model
#H at the end of each iteration we append the number of correctly classified observations
#I printing this array we can see how after each iteration the new count of correctly classified observations is appended 
#J It's easier to see when plot the array
#K The plot is shown

#Iris classification example

In [18]:
import sklearn as sklearn
from sklearn import cluster
import pandas as pd

data = sklearn.datasets.load_iris()  #A                        
X = pd.DataFrame(data.data, columns = list(data.feature_names))  #B 
print X[:5] #C
model   = cluster.KMeans(n_clusters=3, random_state=25)  #D                
results = model.fit(X) #E            
X["cluster"] = results.predict(X) #F       
X["target"] = data.target #G
X["c"] = "lookatmeIamimportant" #H
print X[:5] #I
classification_result = X[["cluster", "target","c"]].groupby(["cluster","target"]).agg("count")  #J
print(classification_result)#K

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2
   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   cluster  target                     c  
0        0       0  lookat

In [ ]:
#A load in the iris (flowers) data of scikit learn
#B transform the iris data into a pandas dataframe
#C print the first 5 observations of the dataframe to the screen, now we can clearly see the 4 variables: sepal length, sepal width, petal length and petal width
#D initialise a kmeans cluster model with 3 clusters. the random_state is just a random seed, if you don't put it, the seed will also be random.
# we opt for 3 clusters because we saw in the last listing this might be a good compromise between complexity and performance
#E fit the model to the data. All variables are considered independent variables, there is no target variable (y) in unsupervised learninh
#F add another variable called "cluster" to the dataframe. This indicates the cluster membership of every flower in the dataset
#G let's finally add a target variable (y) to the dataframe 
#H adding a variable "c" is just a little trick we use to do a count later. the value here is really arbitrary since we just need a column to count the rows
#I there are 3 parts to this code, first we select the "cluster", "target" and "c" column. Then we group by the "cluster" and "target" column. Finally we aggregate the row of the group by with a simple count aggregation
#K the matrix this classification result represents gives us an indication of whether our clustering was successful. For cluster 0, we are spot on, on clusters 1 and 2 there has been a slight mixup but in total we only get 16 (14+2) misclassifications out of 150.  